### ISSUE TITLE
Tests manuels  0.93

### ISSUE THREAD

**Issue by jgirardet** [jgirardet/MyCartable#84]
# Précédure de Tests manuels

Cocher les cases pour chaque étape. En cas de problème ne pas modifier cette partie, ajouter des
commentaires à la suite de ce message pour *chaque problème différent*

## A) Général

- [x] Lancement
- [x] Ouverture : rien n'est sélectionné, rien n'apparait à droite et au milieu
- [x] Les récents sont visibles

## B) Gestion des Matieres

- [x] Aller dans fichier modifier les matières
- [x] Créer un nouveau groupe: "groupe 1"
- [x] Créer un nouveau groupe: "groupe 2"
- [x] Déplacer "groupe 1" sur "groupe 2"
- [x] Déplacer "groupe 2" sous "groupe 1"
- [x] Choisir sa couleur
- [x] Créer un permière matiere "mat 1"
- [x] Créer une deuxième matiere "mat 2"
- [x] Créer un activité "ac 1" dans "mat 1"
- [x] Créer un activité "ac 2" dans "mat 1"
- [x] Déplacer "ac 1" sur "ac 2"
- [x] Déplacer "ac 2" sous "ac 1"
- [x] Créer un activité "ac 3" dans "mat 2"
- [x] Déplacer "mat 2" sous "mat 1"
- [x] Déplacer "mat 1" sur "mat 2"
- [x] Constater le bon changement de couleur
- [x] Quitter le choix des matières en cliqant sur le cotés

## C) Utilisation matieres et rubriques
- [x] Click sur le bouton: les matières apparaissent
- [x] constater "mat 2 en premier, mat 1 en deuxième"
- [x] Sélection change la matiere
- [x] Le changement de matière change bien les rubriques
- [x] Sélectonner Mat 1
- [x] Constater "ac 2" au dessus de "ac 1" 
- [x] Sélectonner Mat 2
- [x] Constater "ac 3"
- [x] Cliquer droit sur ac2
- [x] Constater qu'un matière se créee
- [x] La barre d'outil est visible
- [x] Le curseur est dans la zone de titre
- [x] taper "titre 1" constaer la mier à jour dans les récents (1er de la liste) et sous  "ac 2"
- [x] Sous "ac 2", cliquer "droit" sur "titre 1", le déplacer dans mat1->ac1
- [x] Constater "titre 1" est passé de "ac 2" à "ac 1"
- [x] Cliquer droit sur "titre 1" et le déplacer dans mat2->ac3
- [x] Constater "titre 1" a "disparu"
- [x] Aller dans Mat2
- [x] Constater que "titre 1" est bien dans "ac 3"

## D) Récents
- [x] les couleurs sont en accords avec les matières
- [x] clique sur un récent affiche la page et change la matière à droite

## E) Page
- [x] Créer une nouvelle page dans "Mat 1/Ac1"
- [x] Taper un titre trop long pour (par rapport à la place) et constater que la taille du texte s'adapte
- [x] Effacer un partie du titre et voir que la taille du texte réaugmente
- [x] Appuyer sur `Entrée`
- [x] Constater que le titre n'a pas bougé, Toujours centré et parfaitement visible
- [x] Constater une zone de texte a été crée
- [x] Faire Ctrl + t : une zone de texte est crée à la suite
- [x] Faire Ctrl + e : une zone d'équation est crée à la suite
- [x] cliquer sur l"icone "ajout de texte"
- [x] Entre 2 zones : faire `Maj + clique droit`
- [x] le menu apparait
- [x] Pour chaque icone ajouter un élément
- [ ] Le menu disparait quand on sélectionne un élément
- [x] L'élément s'insère bien "entre les 2 zones"
    - [x] tester avec texte 
    - [x] tester avec image 
    - [x] tester avec equation 
    - [x] tester avec opération (1 seule) 
    - [x] tester avec tableau
- [x]  Faire `Maj + click gauche en retant appuyé`
- [x] Déplacer vers le haut puis relacher. Constater le changement de position
- [x] Déplacer vers le puis  relacher. Constater le changement de position
    - [x] tester avec texte 
    - [x] tester avec image 
    - [x] tester avec equation 
    - [x] tester avec opération (1 seule) 
    - [x] tester avec tableau
- [x] scroller avec la molette, constater l'absence de saccade
- [x] scroller avec la bare de scroll, constater l'absence de saccade
- [x] faire  `Maj + clique du milieu` sur chaque section créé
- [x] confirmer la suppression
- [x] la zone disparait.
    - [x] tester avec texte 
    - [x] tester avec image 
    - [x] tester avec equation 
    - [x] tester avec opération (1 seule) 
    - [x] tester avec tableau

## F) Zone de Texte
- [x] taper quelques mot puis `Entrée`
- [x] taper "#", `espace`,  "titre 1" puis "Entrée`
- [x] Constater que le titre est créé`et bien formatté
- [x] taper "##", `espace`,  "titre 2" puis "Entrée`
- [x] Constater que le titre est créé`et bien formatté
- [x] taper "####", `espace`,  "titre 3" puis "Entrée`
- [x] Constater que le titre est créé`et bien formatté
- [x] taper "####", `espace`,  "titre 4" puis "Entrée`
- [x] Constater que le titre est créé`et bien formatté
- [x] Constater que les tailles et les couleur sont différents
- [x] Refaire la même chose mais en mettant les "#" à la fin de la ligne
- [x] Constater que le formattage est bon.
- [x] taper 2 lignes de texte au hasard.
- [x] Tester les 4 couleurs de texte (après avoir sélectionné le texte)
- [x] Tester les 4 couleurs de soulignage texte (après avoir sélectionné le texte)
- [ ] Tester les raccourcis clavies de formattage : Ctrl+1,Ctrl+2,Ctrl+3,Ctrl+4,, Ctrl-U

# G) Equation
- [x] taper l'équation suivante: 234/234 + 234234/234324
- [x] bonne présentation
- [x] se déplacer avec les flêches
- [x] Se positionner en haut : faire `Entrée`, positionnement en bas
- [x] Se positionner en bas : faire `Entrée`, positionnement au milieu, après.

## H) Image
- [x] importer une image
- [x] importer un pdf
- [x] import un pdf avec plusieurs pages
- [x] `Clique Gauche ` sur une page, taper du texte
- [x] Changer la taille avec `Ctrl +` et `Ctrl -`.
- [x] `Clique Gauche ` sur une page, taper du texte. La taille est la même que la dernière choisie
- [x] tester le surlignage
    - [x] rouge
    - [x] bleu
    - [x] vert
    - [x] noir
- [x] tester le soulignage
    - [x] rouge
    - [x] bleu
    - [x] vert
    - [x] noir    
- [x] tester le changement de couleur du texte
    - [x] rouge
    - [x] bleu
    - [x] vert
    - [x] noir
- [x] Faire `Ctrl + clique droit` pour surligner quelque chose.
- [x] sélectionner un outil, tracer.
    - [x] trait
    - [x] rectangle vide
    - [x] rectangle plein
    - [x] rectangle ellipse
    - [x] rectangle fleche
- [x] Faire `clique droit` sur un dessin:
    - [x] changer le contour
    - [x] changer la couleur de remplissage
    - [x] changer l'épaisseur du trait
    - [x] changer la transparence
- [x] Faire `clique droit` n'importe où sur l'image.
    - [x] choisir l'épaisseur
    - [x] choisir la couleur
    - [x] choisir l'outil
    - [x] tracer, constater que le résultat est celui attendu
- [x] Deplacer chaque élément créé avec `Ctrl + clique gauche`
    - [x] texte
    - [x] trait
    - [x] rectangle vide
    - [x] rectangle plein
    - [x] rectangle ellipse
    - [x] rectangle fleche
- [x] Supprimer les dessins avec  `clique du milieu`
    - [x] trait
    - [x] rectangle vide
    - [x] rectangle plein
    - [x] rectangle ellipse
    - [x] rectangle fleche
- [x] faire clique droit sur l'image
    - [x] pivoter à gauche
    - [x] pivoter à droite
    
## I) Operations
- [x] Faire une addition : 234+435 (remplir juste, le résultat importe peu)
    - [x] Constater qu'après une touche on va bien dans la bonne case
- [x] Faire une multiplication: 2334*234 (remplir juste, le résultat importe peu)
    - [x] Constater qu'après une touche on va bien dans la bonne case
    - [x] Constater le soulignement en fonction de la case où l'on se trouve.
- [x] Faire une soustraction: 234-34 (remplir juste, le résultat importe peu)
    - [x] Constater qu'après une touche on va bien dans la bonne case
    - [x] utiliser les retenues avec la touche "*"
- [x] Faire une division: 234/34 (remplir juste, le résultat importe peu)
    - [x] Constater qu'après une touche on va bien dans la bonne case
    - [x] utiliser les retenues avec la touche "*"
    - [x] utilser `Entree` pour passer d'un côté à l'autre
    - [x] utilser `-` pour aller à la ligne d'une soustraction
    - [x] utilser `+` pour abaisser un chiffre

## J) Tableaux
- [x] Tester les 4 modèles et constater le bon résultat
- [x] Tester les 1 et 4 colonnes et constater le bon résultat
- [x] Tester les 1 et 4 lignes et constater le bon résultat
- [x] créer un tableau vide 6 colinnes et 10 lignes
- [x] écrire du texte au hasard à l'intérieur, voir si ça marche
- [x] écrire du texte sur plusieurs lignes en faisant `Entréé`., voir si ça marche
- [x] se déplacer avec les flèches
- [x] Faire `Click droit`, Tester remplissage
- [x] Faire `Click droit`, Tester couleur du texte
- [x] Faire `Click droit`, Tester soulignage
- [x] Sélectionner plusieurs cellules avec `Ctrl  + clique gauche`
- [x] ces cellules sont bleutés
- [x] Faire `Click droit`, Tester remplissage des cellules sélectionnées
- [x] resélectionner
- [x] Faire `Click droit`, Tester couleur du texte des cellules sélectionnées
- [x] resélectionner
- [x] Faire `Click droit`, Tester soulignage du texte des cellules sélectionnées
- [x] FAire `Click droit`, tester `ajouter une colonne`
- [x] FAire `Click droit`, tester `ajouter une colonne à la fin`
- [x] FAire `Click droit`, tester `supprimer une colonne`
- [x] FAire `Click droit`, tester `ajouter une ligne`
- [x] FAire `Click droit`, tester `ajouter une ligne à la fin`
- [x] FAire `Click droit`, tester `supprimer une ligne`
    
## K) Barre d'outil
- [x] Ajouter un texte
- [x] Ajouter une équation
- [x] Ajouter une opération
- [x] Ajouter un tableau
- [x] Exporter en ".odt"
    - [x] libreoffice doit s'ouvrir
    - [x] vérifier nom, prenom, classe
    - [x] conster que le résultat correspond
- [x] Exporter en ".pdf"
    - [x] le pdf doit s'ouvrir
    - [x] conster que le résultat correspond
    - [x] vérifier nom, prenom, classe
    
## L) Tout effacer
- [x] Aller dans "Fichiers ->modifier matière"
- [x] Constater le nombre de page et de rubriques pour "mat 1" et "mat 2"
- [x] affiches les  rubriques pour "mat 1" et "mat 2"
- [x] voir qu'il n'y a pas de bouton effacer si le nombre de page est supérieur à 0
- [x] Quitter changer matiere
- [x] supprimer les pages crées pour ce test avec l'icone poubelle dans les matières "MAt 1" et "Mat 2"
- [x] voir qu'une page supprimée disparait dans les récents  à gauche et dans les matière à droite.
- [x] retourner dans changer matières
- [x] supprimer "ac 3" dans " mat 2"
- [x] supprimer "mat 2"
- [x] supprimer "groupe 1"
- [x] supprimer "groupe 2"
- [x] quitter "modification matiere"
- [x] constater que les matieres ont disparu en cliquant sur le bouton de choix des matières

**Comment by axelg17** [comment]
controle 1 en rouge  ne marche pas

**Comment by axelg17** [comment]
bug pour effacer matiere 2 à revoir
pas d'affichage matieres au débtut
